# Generated by Django 3.2.8 on 2022-08-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0005_auto_20220822_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='shortener.urlmap')),
            ],
            options={
                'verbose_name': 'ShortUrl',
                'verbose_name_plural': 'ShortUrls',
            },
        ),
    ]
